FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]


# docker-machine ip Char

# docker run -it debian bash

# docker build -t ruby:v1 . // build
# docker images - check for teamspeak image
# docker run ruby:v1

# docker build -t ft-rails:on-build .